name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bacta-ci

    - name: Compile the package
      run: docker run -e DATA_DIR=data bacta-ci python -m build

    - name: Run the tests
      run: docker run -e DATA_DIR=data bacta-ci pytest tests/
